// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file caip/account.proto (package printrfi.caip, syntax proto3)
/* eslint-disable */
// @ts-nocheck
import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message printrfi.caip.Account
 */
export class Account extends Message<Account> {
  /**
   * @generated from field: string chain_id = 1;
   */
  chainId = "";

  /**
   * @generated from field: string address = 2;
   */
  address = "";

  constructor(data?: PartialMessage<Account>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.caip.Account";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "chain_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Account {
    return new Account().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Account {
    return new Account().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Account {
    return new Account().fromJsonString(jsonString, options);
  }

  static equals(
    a: Account | PlainMessage<Account> | undefined,
    b: Account | PlainMessage<Account> | undefined,
  ): boolean {
    return proto3.util.equals(Account, a, b);
  }
}

/**
 * @generated from message printrfi.caip.Chain
 */
export class Chain extends Message<Chain> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<Chain>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.caip.Chain";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Chain {
    return new Chain().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Chain {
    return new Chain().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Chain {
    return new Chain().fromJsonString(jsonString, options);
  }

  static equals(
    a: Chain | PlainMessage<Chain> | undefined,
    b: Chain | PlainMessage<Chain> | undefined,
  ): boolean {
    return proto3.util.equals(Chain, a, b);
  }
}
