// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file api/api.proto (package printrfi.api, syntax proto3)
// Minimal version - only ProtocolFees for fee claiming
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { ProtocolFeesRequest, ProtocolFeesResponse } from "./api_pb.js";

/**
 * Minimal Backend service for fee operations
 */
export const Backend = {
  typeName: "printrfi.api.Backend",
  methods: {
    /**
     * Query accumulated protocol/liquidity fees across chains and return
     * distribution breakdowns and optional collection payloads per chain.
     *
     * @generated from rpc printrfi.api.Backend.ProtocolFees
     */
    protocolFees: {
      name: "ProtocolFees",
      I: ProtocolFeesRequest,
      O: ProtocolFeesResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
