// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file api/misc.proto (package printrfi.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint/suspicious/noShadowRestrictedNames: Generated proto code

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Account, Chain } from "../caip/account_pb.js";
import { BigInt } from "../pig/pig_pb.js";

/**
 * @generated from enum printrfi.api.SortDirectionV2
 */
export enum SortDirectionV2 {
  /**
   * @generated from enum value: SORT_DIRECTION_V2_DESC = 0;
   */
  DESC = 0,

  /**
   * @generated from enum value: SORT_DIRECTION_V2_ASC = 1;
   */
  ASC = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(SortDirectionV2)
proto3.util.setEnumType(SortDirectionV2, "printrfi.api.SortDirectionV2", [
  { no: 0, name: "SORT_DIRECTION_V2_DESC" },
  { no: 1, name: "SORT_DIRECTION_V2_ASC" },
]);

/**
 * Deprecated: only used for backwards compatibility
 * This msg is not used for persistent data so it is safe to delete once replaced with v1 equivalent.
 *
 * @generated from message printrfi.api.AssetAmountV0
 */
export class AssetAmountV0 extends Message<AssetAmountV0> {
  /**
   * caip2 prefixed identifier
   *
   * @generated from field: printrfi.caip.Account asset = 1;
   */
  asset?: Account;

  /**
   * the amount in the smallest unit of the asset (e.g. wei)
   *
   * @generated from field: printrfi.pig.BigInt amount_atomic = 2;
   */
  amountAtomic?: BigInt;

  /**
   * the number of decimals of the asset
   *
   * @generated from field: uint32 decimals = 3;
   */
  decimals = 0;

  /**
   * the price of the asset in USD
   *
   * @generated from field: double price_usd = 4;
   */
  priceUsd = 0;

  /**
   * the value of the asset in USD
   *
   * @generated from field: double amount_usd = 5;
   */
  amountUsd = 0;

  constructor(data?: PartialMessage<AssetAmountV0>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.AssetAmountV0";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset", kind: "message", T: Account },
    { no: 2, name: "amount_atomic", kind: "message", T: BigInt },
    { no: 3, name: "decimals", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "price_usd", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "amount_usd", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AssetAmountV0 {
    return new AssetAmountV0().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AssetAmountV0 {
    return new AssetAmountV0().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AssetAmountV0 {
    return new AssetAmountV0().fromJsonString(jsonString, options);
  }

  static equals(
    a: AssetAmountV0 | PlainMessage<AssetAmountV0> | undefined,
    b: AssetAmountV0 | PlainMessage<AssetAmountV0> | undefined,
  ): boolean {
    return proto3.util.equals(AssetAmountV0, a, b);
  }
}

/**
 * Deprecated: only used in deprecated ImmutableCurveCreationParams
 *
 * @generated from message printrfi.api.CreatorAddresses
 */
export class CreatorAddresses extends Message<CreatorAddresses> {
  /**
   * @generated from field: string evm = 1;
   */
  evm = "";

  /**
   * @generated from field: string svm = 2;
   */
  svm = "";

  /**
   * @generated from field: string move = 3;
   */
  move = "";

  constructor(data?: PartialMessage<CreatorAddresses>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.CreatorAddresses";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "evm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "svm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "move", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatorAddresses {
    return new CreatorAddresses().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatorAddresses {
    return new CreatorAddresses().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatorAddresses {
    return new CreatorAddresses().fromJsonString(jsonString, options);
  }

  static equals(
    a: CreatorAddresses | PlainMessage<CreatorAddresses> | undefined,
    b: CreatorAddresses | PlainMessage<CreatorAddresses> | undefined,
  ): boolean {
    return proto3.util.equals(CreatorAddresses, a, b);
  }
}

/**
 * Deprecated: only used for backwards compatibility
 * This msg is not used for persistent data so it is safe to delete once replaced with v1 equivalent.
 *
 * @generated from message printrfi.api.ImmutableCurveCreationParamsV0
 */
export class ImmutableCurveCreationParamsV0 extends Message<ImmutableCurveCreationParamsV0> {
  /**
   * @generated from field: string token_id = 1;
   */
  tokenId = "";

  /**
   * @generated from field: bytes salt = 2;
   */
  salt = new Uint8Array(0);

  /**
   * Use creator_addresses field instead;
   *
   * @generated from field: string creator_address = 3 [deprecated = true];
   * @deprecated
   */
  creatorAddress = "";

  /**
   * @generated from field: printrfi.api.CreatorAddresses creator_addresses = 4;
   */
  creatorAddresses?: CreatorAddresses;

  /**
   * @generated from field: string name = 5;
   */
  name = "";

  /**
   * @generated from field: string symbol = 6;
   */
  symbol = "";

  /**
   * @generated from field: string home_chain_id = 7 [deprecated = true];
   * @deprecated
   */
  homeChainId = "";

  /**
   * @generated from field: repeated string chain_ids = 8;
   */
  chainIds: string[] = [];

  /**
   * @generated from field: repeated string base_pair_addresses = 9;
   */
  basePairAddresses: string[] = [];

  /**
   * @generated from field: string reference_asset_id = 10;
   */
  referenceAssetId = "";

  /**
   * @generated from field: int32 max_supply_exponent = 11;
   */
  maxSupplyExponent = 0;

  /**
   * @generated from field: string graduation_threshold_ref_atomic = 12;
   */
  graduationThresholdRefAtomic = "";

  /**
   * @generated from field: int32 completion_threshold_basis_points = 13;
   */
  completionThresholdBasisPoints = 0;

  /**
   * @generated from field: string initial_price_ref_atomic = 14;
   */
  initialPriceRefAtomic = "";

  /**
   * @generated from field: string initial_spend_ref_atomic = 15;
   */
  initialSpendRefAtomic = "";

  /**
   * Source of truth for what's actually on-chain.
   *
   * @generated from field: printrfi.api.IPrintrStorageTokenParamsV0 storage_token_params = 16;
   */
  storageTokenParams?: IPrintrStorageTokenParamsV0;

  /**
   * @generated from field: printrfi.caip.Account payer = 17;
   */
  payer?: Account;

  constructor(data?: PartialMessage<ImmutableCurveCreationParamsV0>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.ImmutableCurveCreationParamsV0";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "salt", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "creator_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "creator_addresses", kind: "message", T: CreatorAddresses },
    { no: 5, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "symbol", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "home_chain_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "chain_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    {
      no: 9,
      name: "base_pair_addresses",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
      repeated: true,
    },
    { no: 10, name: "reference_asset_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "max_supply_exponent", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    {
      no: 12,
      name: "graduation_threshold_ref_atomic",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
    },
    {
      no: 13,
      name: "completion_threshold_basis_points",
      kind: "scalar",
      T: 5 /* ScalarType.INT32 */,
    },
    { no: 14, name: "initial_price_ref_atomic", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "initial_spend_ref_atomic", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "storage_token_params", kind: "message", T: IPrintrStorageTokenParamsV0 },
    { no: 17, name: "payer", kind: "message", T: Account },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): ImmutableCurveCreationParamsV0 {
    return new ImmutableCurveCreationParamsV0().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): ImmutableCurveCreationParamsV0 {
    return new ImmutableCurveCreationParamsV0().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): ImmutableCurveCreationParamsV0 {
    return new ImmutableCurveCreationParamsV0().fromJsonString(jsonString, options);
  }

  static equals(
    a: ImmutableCurveCreationParamsV0 | PlainMessage<ImmutableCurveCreationParamsV0> | undefined,
    b: ImmutableCurveCreationParamsV0 | PlainMessage<ImmutableCurveCreationParamsV0> | undefined,
  ): boolean {
    return proto3.util.equals(ImmutableCurveCreationParamsV0, a, b);
  }
}

/**
 * Deprecated: only used for backwards compatibility
 * This msg is not used for persistent data so it is safe to delete once replaced with v1 equivalent.
 *
 * @generated from message printrfi.api.IPrintrStorageTokenParamsV0
 */
export class IPrintrStorageTokenParamsV0 extends Message<IPrintrStorageTokenParamsV0> {
  /**
   * @generated from field: bytes salt = 1;
   */
  salt = new Uint8Array(0);

  /**
   * @generated from field: bytes creator_addresses = 2;
   */
  creatorAddresses = new Uint8Array(0);

  /**
   * @generated from field: bytes name = 3;
   */
  name = new Uint8Array(0);

  /**
   * @generated from field: bytes symbol = 4;
   */
  symbol = new Uint8Array(0);

  /**
   * @generated from field: bytes packed_params = 5;
   */
  packedParams = new Uint8Array(0);

  /**
   * @generated from field: repeated bytes chains = 6;
   */
  chains: Uint8Array[] = [];

  /**
   * @generated from field: repeated bytes base_pairs = 7;
   */
  basePairs: Uint8Array[] = [];

  /**
   * @generated from field: bytes base_prices = 8;
   */
  basePrices = new Uint8Array(0);

  constructor(data?: PartialMessage<IPrintrStorageTokenParamsV0>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.IPrintrStorageTokenParamsV0";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "salt", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "creator_addresses", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "name", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "symbol", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "packed_params", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 6, name: "chains", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
    { no: 7, name: "base_pairs", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
    { no: 8, name: "base_prices", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): IPrintrStorageTokenParamsV0 {
    return new IPrintrStorageTokenParamsV0().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): IPrintrStorageTokenParamsV0 {
    return new IPrintrStorageTokenParamsV0().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): IPrintrStorageTokenParamsV0 {
    return new IPrintrStorageTokenParamsV0().fromJsonString(jsonString, options);
  }

  static equals(
    a: IPrintrStorageTokenParamsV0 | PlainMessage<IPrintrStorageTokenParamsV0> | undefined,
    b: IPrintrStorageTokenParamsV0 | PlainMessage<IPrintrStorageTokenParamsV0> | undefined,
  ): boolean {
    return proto3.util.equals(IPrintrStorageTokenParamsV0, a, b);
  }
}

/**
 * Deprecated: only used for backwards compatibility
 * This msg is not used for persistent data so it is safe to delete once replaced with v1 equivalent.
 *
 * @generated from message printrfi.api.MutableTokenMetadataV0
 */
export class MutableTokenMetadataV0 extends Message<MutableTokenMetadataV0> {
  /**
   * @generated from field: string description = 1;
   */
  description = "";

  /**
   * @generated from field: string image_url = 2;
   */
  imageUrl = "";

  /**
   * @generated from field: string external_url_website = 3;
   */
  externalUrlWebsite = "";

  /**
   * @generated from field: string external_url_telegram = 4;
   */
  externalUrlTelegram = "";

  /**
   * @generated from field: string external_url_x = 5;
   */
  externalUrlX = "";

  /**
   * @generated from field: string external_url_github = 6;
   */
  externalUrlGithub = "";

  constructor(data?: PartialMessage<MutableTokenMetadataV0>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.MutableTokenMetadataV0";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "external_url_website", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "external_url_telegram", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "external_url_x", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "external_url_github", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): MutableTokenMetadataV0 {
    return new MutableTokenMetadataV0().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): MutableTokenMetadataV0 {
    return new MutableTokenMetadataV0().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): MutableTokenMetadataV0 {
    return new MutableTokenMetadataV0().fromJsonString(jsonString, options);
  }

  static equals(
    a: MutableTokenMetadataV0 | PlainMessage<MutableTokenMetadataV0> | undefined,
    b: MutableTokenMetadataV0 | PlainMessage<MutableTokenMetadataV0> | undefined,
  ): boolean {
    return proto3.util.equals(MutableTokenMetadataV0, a, b);
  }
}

/**
 * Identifies some amount of a specific asset.
 *
 * @generated from message printrfi.api.AssetAmountV1
 */
export class AssetAmountV1 extends Message<AssetAmountV1> {
  /**
   * Required.
   *
   * @generated from field: printrfi.caip.Account asset = 1;
   */
  asset?: Account;

  /**
   * Required.
   *
   * @generated from field: printrfi.api.TokenAmount amount = 2;
   */
  amount?: TokenAmount;

  constructor(data?: PartialMessage<AssetAmountV1>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.AssetAmountV1";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset", kind: "message", T: Account },
    { no: 2, name: "amount", kind: "message", T: TokenAmount },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AssetAmountV1 {
    return new AssetAmountV1().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AssetAmountV1 {
    return new AssetAmountV1().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AssetAmountV1 {
    return new AssetAmountV1().fromJsonString(jsonString, options);
  }

  static equals(
    a: AssetAmountV1 | PlainMessage<AssetAmountV1> | undefined,
    b: AssetAmountV1 | PlainMessage<AssetAmountV1> | undefined,
  ): boolean {
    return proto3.util.equals(AssetAmountV1, a, b);
  }
}

/**
 * @generated from message printrfi.api.TokenAmount
 */
export class TokenAmount extends Message<TokenAmount> {
  /**
   * In the respective token's smallest denomination.
   *
   * Required.
   *
   * @generated from field: string atomic = 1;
   */
  atomic = "";

  /**
   * Formatted with appropriate decimal places.
   *
   * Required.
   *
   * @generated from field: string display = 2;
   */
  display = "";

  /**
   * Required.
   *
   * @generated from field: uint32 decimals = 3;
   */
  decimals = 0;

  constructor(data?: PartialMessage<TokenAmount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.TokenAmount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "atomic", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "decimals", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TokenAmount {
    return new TokenAmount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TokenAmount {
    return new TokenAmount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TokenAmount {
    return new TokenAmount().fromJsonString(jsonString, options);
  }

  static equals(
    a: TokenAmount | PlainMessage<TokenAmount> | undefined,
    b: TokenAmount | PlainMessage<TokenAmount> | undefined,
  ): boolean {
    return proto3.util.equals(TokenAmount, a, b);
  }
}

/**
 * / Conveys an asset price in some reference currency to the caller.
 *
 * @generated from message printrfi.api.PricedAsset
 */
export class PricedAsset extends Message<PricedAsset> {
  /**
   * / The asset being priced.
   * /
   * / Required.
   *
   * @generated from field: printrfi.caip.Account asset = 1;
   */
  asset?: Account;

  /**
   * / The reference currency in which the price is expressed.
   * /
   * / Required.
   *
   * @generated from field: printrfi.caip.Account reference = 2;
   */
  reference?: Account;

  /**
   * / Required.
   *
   * @generated from field: printrfi.api.Price price = 3;
   */
  price?: Price;

  constructor(data?: PartialMessage<PricedAsset>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.PricedAsset";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset", kind: "message", T: Account },
    { no: 2, name: "reference", kind: "message", T: Account },
    { no: 3, name: "price", kind: "message", T: Price },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PricedAsset {
    return new PricedAsset().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PricedAsset {
    return new PricedAsset().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PricedAsset {
    return new PricedAsset().fromJsonString(jsonString, options);
  }

  static equals(
    a: PricedAsset | PlainMessage<PricedAsset> | undefined,
    b: PricedAsset | PlainMessage<PricedAsset> | undefined,
  ): boolean {
    return proto3.util.equals(PricedAsset, a, b);
  }
}

/**
 * / Conveys an asset price in the bald eagle style.
 *
 * @generated from message printrfi.api.UsdPricedAsset
 */
export class UsdPricedAsset extends Message<UsdPricedAsset> {
  /**
   * / The asset being priced.
   * /
   * / Required.
   *
   * @generated from field: printrfi.caip.Account asset = 1;
   */
  asset?: Account;

  /**
   * / Required.
   *
   * @generated from field: printrfi.api.Price price = 2;
   */
  price?: Price;

  constructor(data?: PartialMessage<UsdPricedAsset>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.UsdPricedAsset";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset", kind: "message", T: Account },
    { no: 2, name: "price", kind: "message", T: Price },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsdPricedAsset {
    return new UsdPricedAsset().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsdPricedAsset {
    return new UsdPricedAsset().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsdPricedAsset {
    return new UsdPricedAsset().fromJsonString(jsonString, options);
  }

  static equals(
    a: UsdPricedAsset | PlainMessage<UsdPricedAsset> | undefined,
    b: UsdPricedAsset | PlainMessage<UsdPricedAsset> | undefined,
  ): boolean {
    return proto3.util.equals(UsdPricedAsset, a, b);
  }
}

/**
 * / Price of an asset in some reference currency.
 *
 * @generated from message printrfi.api.Price
 */
export class Price extends Message<Price> {
  /**
   * / One of asset in worth this much reference.
   * /
   * / E.g. 1 $SOL = 213 $USDC would be "213.0".
   * /
   * / Required.
   *
   * @generated from field: string display = 1;
   */
  display = "";

  /**
   * / Price scaled by 10^18 for precision.
   * /
   * / E.g. 1 $SOL = 213 $USDC would be "213000000000000000000".
   * /
   * / Required.
   *
   * @generated from field: string x18 = 2;
   */
  x18 = "";

  constructor(data?: PartialMessage<Price>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.Price";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "display", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "x18", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Price {
    return new Price().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Price {
    return new Price().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Price {
    return new Price().fromJsonString(jsonString, options);
  }

  static equals(
    a: Price | PlainMessage<Price> | undefined,
    b: Price | PlainMessage<Price> | undefined,
  ): boolean {
    return proto3.util.equals(Price, a, b);
  }
}

/**
 * Uniquely identifies a transaction on some chain.
 *
 * @generated from message printrfi.api.TransactionReference
 */
export class TransactionReference extends Message<TransactionReference> {
  /**
   * @generated from field: printrfi.caip.Chain chain = 1;
   */
  chain?: Chain;

  /**
   * The transaction ID / hash / whatever a particular chain uses to identify a transaction.
   *
   * @generated from field: string id = 2;
   */
  id = "";

  /**
   * Which block was this transaction included in.
   *
   * @generated from field: string block_number = 3;
   */
  blockNumber = "";

  /**
   * When was this transaction included in a block.
   *
   * @generated from field: google.protobuf.Timestamp block_timestamp = 4;
   */
  blockTimestamp?: Timestamp;

  constructor(data?: PartialMessage<TransactionReference>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.TransactionReference";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "chain", kind: "message", T: Chain },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "block_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "block_timestamp", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionReference {
    return new TransactionReference().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionReference {
    return new TransactionReference().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): TransactionReference {
    return new TransactionReference().fromJsonString(jsonString, options);
  }

  static equals(
    a: TransactionReference | PlainMessage<TransactionReference> | undefined,
    b: TransactionReference | PlainMessage<TransactionReference> | undefined,
  ): boolean {
    return proto3.util.equals(TransactionReference, a, b);
  }
}

/**
 * Basis points, i.e. hundredths of a percent.
 * 100 bps = 1%.
 *
 * @generated from message printrfi.api.Bps
 */
export class Bps extends Message<Bps> {
  /**
   * @generated from field: uint32 bps = 1;
   */
  bps = 0;

  constructor(data?: PartialMessage<Bps>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.Bps";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bps", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Bps {
    return new Bps().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Bps {
    return new Bps().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Bps {
    return new Bps().fromJsonString(jsonString, options);
  }

  static equals(
    a: Bps | PlainMessage<Bps> | undefined,
    b: Bps | PlainMessage<Bps> | undefined,
  ): boolean {
    return proto3.util.equals(Bps, a, b);
  }
}
