// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file api/payload.proto (package printrfi.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Account } from "../caip/account_pb.js";

/**
 * Payload that can be signed to execute some intent.
 *
 * @generated from message printrfi.api.TxPayload
 */
export class TxPayload extends Message<TxPayload> {
  /**
   * @generated from oneof printrfi.api.TxPayload.payload
   */
  payload:
    | {
        /**
         * @generated from field: printrfi.api.EvmTxPayload evm = 1;
         */
        value: EvmTxPayload;
        case: "evm";
      }
    | {
        /**
         * @generated from field: printrfi.api.SolanaTxPayload solana = 2;
         */
        value: SolanaTxPayload;
        case: "solana";
      }
    | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<TxPayload>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.TxPayload";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "evm", kind: "message", T: EvmTxPayload, oneof: "payload" },
    { no: 2, name: "solana", kind: "message", T: SolanaTxPayload, oneof: "payload" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TxPayload {
    return new TxPayload().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TxPayload {
    return new TxPayload().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TxPayload {
    return new TxPayload().fromJsonString(jsonString, options);
  }

  static equals(
    a: TxPayload | PlainMessage<TxPayload> | undefined,
    b: TxPayload | PlainMessage<TxPayload> | undefined,
  ): boolean {
    return proto3.util.equals(TxPayload, a, b);
  }
}

/**
 * @generated from message printrfi.api.EvmTxPayload
 */
export class EvmTxPayload extends Message<EvmTxPayload> {
  /**
   * Where to send the tx to.
   *
   * @generated from field: printrfi.caip.Account target_contract = 1;
   */
  targetContract?: Account;

  /**
   * Gas limit to use for the transaction.
   *
   * @generated from field: uint64 gas_limit = 2;
   */
  gasLimit = protoInt64.zero;

  /**
   * Native value to send with the transaction in the respective chain's smallest denomination.
   *
   * @generated from field: string msg_value = 3;
   */
  msgValue = "";

  /**
   * Expecting EVM calldata starting with "0x" prefix.
   *
   * @generated from field: string hex_encoded_prefixed_calldata = 4;
   */
  hexEncodedPrefixedCalldata = "";

  constructor(data?: PartialMessage<EvmTxPayload>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.EvmTxPayload";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_contract", kind: "message", T: Account },
    { no: 2, name: "gas_limit", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "msg_value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "hex_encoded_prefixed_calldata", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EvmTxPayload {
    return new EvmTxPayload().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EvmTxPayload {
    return new EvmTxPayload().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EvmTxPayload {
    return new EvmTxPayload().fromJsonString(jsonString, options);
  }

  static equals(
    a: EvmTxPayload | PlainMessage<EvmTxPayload> | undefined,
    b: EvmTxPayload | PlainMessage<EvmTxPayload> | undefined,
  ): boolean {
    return proto3.util.equals(EvmTxPayload, a, b);
  }
}

/**
 * @generated from message printrfi.api.SolanaTxPayload
 */
export class SolanaTxPayload extends Message<SolanaTxPayload> {
  /**
   * Create a Solana tx from these instructions, attach blockhash, sign and cook.
   *
   * Required.
   *
   * @generated from field: repeated printrfi.api.SolanaIx ixs = 1;
   */
  ixs: SolanaIx[] = [];

  /**
   * Zero or more lookup tables to minimize the tx size.
   *
   * @generated from field: repeated printrfi.caip.Account lookup_tables = 2;
   */
  lookupTables: Account[] = [];

  constructor(data?: PartialMessage<SolanaTxPayload>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.SolanaTxPayload";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ixs", kind: "message", T: SolanaIx, repeated: true },
    { no: 2, name: "lookup_tables", kind: "message", T: Account, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaTxPayload {
    return new SolanaTxPayload().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaTxPayload {
    return new SolanaTxPayload().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaTxPayload {
    return new SolanaTxPayload().fromJsonString(jsonString, options);
  }

  static equals(
    a: SolanaTxPayload | PlainMessage<SolanaTxPayload> | undefined,
    b: SolanaTxPayload | PlainMessage<SolanaTxPayload> | undefined,
  ): boolean {
    return proto3.util.equals(SolanaTxPayload, a, b);
  }
}

/**
 * Solana ixs can be used to build a tx
 *
 * @generated from message printrfi.api.SolanaIx
 */
export class SolanaIx extends Message<SolanaIx> {
  /**
   * Which program to call.
   *
   * Required.
   *
   * @generated from field: printrfi.caip.Account program_id = 1;
   */
  programId?: Account;

  /**
   * The accounts to pass to the program in the order they are expected.
   *
   * Required.
   * Can be empty.
   *
   * @generated from field: repeated printrfi.api.AccountMeta accounts = 2;
   */
  accounts: AccountMeta[] = [];

  /**
   * Serialized ix params into base64 string.
   *
   * Required.
   *
   * @generated from field: string data_base64 = 3;
   */
  dataBase64 = "";

  constructor(data?: PartialMessage<SolanaIx>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.SolanaIx";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "program_id", kind: "message", T: Account },
    { no: 2, name: "accounts", kind: "message", T: AccountMeta, repeated: true },
    { no: 3, name: "data_base64", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaIx {
    return new SolanaIx().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaIx {
    return new SolanaIx().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaIx {
    return new SolanaIx().fromJsonString(jsonString, options);
  }

  static equals(
    a: SolanaIx | PlainMessage<SolanaIx> | undefined,
    b: SolanaIx | PlainMessage<SolanaIx> | undefined,
  ): boolean {
    return proto3.util.equals(SolanaIx, a, b);
  }
}

/**
 * Used to create a Solana ix
 *
 * @generated from message printrfi.api.AccountMeta
 */
export class AccountMeta extends Message<AccountMeta> {
  /**
   * Required.
   *
   * @generated from field: string pubkey_base58 = 1;
   */
  pubkeyBase58 = "";

  /**
   * Required.
   *
   * @generated from field: bool is_signer = 2;
   */
  isSigner = false;

  /**
   * Required.
   *
   * @generated from field: bool is_writable = 3;
   */
  isWritable = false;

  constructor(data?: PartialMessage<AccountMeta>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.AccountMeta";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pubkey_base58", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "is_signer", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "is_writable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AccountMeta {
    return new AccountMeta().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AccountMeta {
    return new AccountMeta().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AccountMeta {
    return new AccountMeta().fromJsonString(jsonString, options);
  }

  static equals(
    a: AccountMeta | PlainMessage<AccountMeta> | undefined,
    b: AccountMeta | PlainMessage<AccountMeta> | undefined,
  ): boolean {
    return proto3.util.equals(AccountMeta, a, b);
  }
}
