/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/print/quote": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get Token Creation Quote
     * @description Calculates comprehensive costs for creating a token across multiple blockchain networks before
     *     committing to the creation process.
     *
     *     ## Quote Calculation
     *     The quote includes:
     *     - **Deployment Costs**: Gas fees for deploying contracts on each selected chain
     *     - **X-Chain Messaging Fees**: X-chain protocol fees for coordinating deployments
     *     - **Initial Buy Costs**: Amount required for the initial token purchase based on your configuration
     *
     *     ## Chain Specification
     *     The first chain in the array becomes the "home chain" where the primary deployment occurs.
     *     Additional chains receive deployments through cascading x-chain messages.
     */
    post: operations["getPrintQuote"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/print": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Token
     * @description Initiates the creation of a new token with simultaneous deployment across multiple blockchain
     *     networks. This endpoint orchestrates the entire token creation process from initial deployment
     *     to x-chain propagation.
     *
     *     ## Token Creation Process
     *     1. **Validation**: Verifies token metadata and deployment parameters
     *     2. **X-Chain Preparation**: Prepares Axelar messages for remote deployments
     *     3. **Payload Generation**: Creates the transaction calldata for the home chain
     *     4. **Catalog Registration**: Registers the token in Printr's discovery system
     *
     *     ## Creator Account and Home Chains
     *     The creator account is a CAIP-10 account identifier that couples a chain identifier and a
     *     specific address. The single field `creator_account` is used to specify both the creators
     *     wallet address, in addition to the expected home chain for the token.
     *
     *     ## Transaction Execution
     *     The response includes transaction calldata that must be:
     *     1. Signed by the creator's wallet specified in the creator_account field
     *     2. Submitted to the home chain
     *     3. Confirmed on-chain to trigger cascading deployments
     *
     *     ## Image Requirements
     *     Token images must be:
     *     - Base64 encoded
     *     - Maximum 500KB in size
     *     - Square aspect ratio recommended
     *     - GIF, PNG, or JPEG format
     */
    post: operations["printToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tokens/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /**
     * Get Token Details
     * @description Retrieves comprehensive information about a token including metadata and immutable properties of
     *     the bonding curve.
     *
     *     ## Cross-Chain Token Identity
     *     Each token has a unique x-chain identifier that remains consistent across all blockchain deployments.
     *     This enables unified tracking regardless of which chain you're querying from.
     *
     *     ## Identifier
     *     This endpoint accepts two formats for the `id` parameter.
     *
     *     Either Printr specific **Telecoin ID** (hex string). This is a cross-chain unique identifier for the Printr token.
     *     Alternatively, use **Token Contract Address** (CAIP-10 format). This is the token's contract address on a specific chain (<https://chainagnostic.org>)
     *
     *     _DEV NOTE: the token identity description may change when we integrate x-chain Solana deployments._
     */
    get: operations["getToken"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tokens/{id}/deployments": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /**
     * Get Token Deployment Status
     * @description Monitors the real-time deployment status of a token across all target blockchain networks.
     *     Essential for tracking the cascading deployment process after token creation.
     *
     *     ## Deployment Lifecycle
     *     Each chain deployment progresses through these states:
     *     1. `**PENDING**`: The token has been cataloged by the Printr platform, however, we have not seen
     *         any associayed on-chain activity related to the token yet.
     *     2. `**DEPLOYING**`: X-chain message sent via one of our x-chain protocol providers, and we're
     *         awaiting confirmation that the deployment has suceeded.
     *     3. `**LIVE**`: The token has been deployed to the target chain and is ready for trading.
     *     4. `**FAILED**`: Deployment unsuccessful (with error details)
     *
     *     ## X-Chain Messaging
     *     For remote chain deployments, track:
     *     - **Transport Provider**: X-chain messaging protocol (e.g., AXELAR, CORAL, LAYERZERO)
     *     - **Message ID**: The message identifier relevant to the transport protocol.
     *
     *     ## Identifier
     *     This endpoint accepts two formats for the `id` parameter.
     *
     *     Either Printr specific **Telecoin ID** (hex string). This is a cross-chain unique identifier for the Printr token.
     *     Alternatively, use **Token Contract Address** (CAIP-10 format). This is the token's contract address on a specific chain (<https://chainagnostic.org>)
     */
    get: operations["getTokenStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Chain Agnostic Improvement Proposal (CAIP-2) blockchain identifier. Provides a standardized format for identifying any blockchain network regardless of its underlying technology stack. Format: {namespace}:{reference}
     *
     *     Examples:
     *     - eip155:1 - Ethereum Mainnet
     *     - eip155:137 - Polygon
     *     - eip155:8453 - Base
     *     - solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp - Solana Mainnet
     * @example eip155:5000
     * @example solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp
     */
    CAIP_2_Chain: string;
    BigInt: string;
    /**
     * @description Configures the initial token purchase executed during creation. This purchase bootstraps
     *     liquidity in the bonding curve and determines the starting price point. Exactly one
     *     purchase method must be specified.
     *
     *     **Note:** The initial buy is capped to 69% of the total supply.
     *
     *     Options:
     *     - supply_percent: Purchase a percentage of total token supply
     *     - spend_usd: Purchase tokens worth a specific USD amount
     *     - spend_native: Purchase using a specific amount of native tokens
     */
    VariableInitialBuy:
      | {
          /**
           * Format: double
           * @description Percentage of total supply to purchase (0.01-69)
           * @example 10
           */
          supply_percent: number;
        }
      | {
          /**
           * Format: double
           * @description USD amount to spend on initial purchase (must be less than 69% of the total supply)
           * @example 500
           */
          spend_usd: number;
        }
      | {
          /** @description Atomic native token amount to spend (must be less than 69% of the total supply) */
          spend_native: components["schemas"]["BigInt"];
        };
    GetPrintQuote_Request: {
      /**
       * @description Array of CAIP-2 chain identifiers where the token will be deployed.
       *     The first indexed chain will be treaded as the home chain for the
       *     deployment transaction.
       */
      chains: components["schemas"]["CAIP_2_Chain"][];
      initial_buy: components["schemas"]["VariableInitialBuy"];
      /**
       * @description The graduation threshold (bonding curve size) for each chain deployed to. Accepted values: $69,000 or $250,000 USD. Defaults to $69,000 USD.
       * @enum {integer}
       */
      graduation_threshold_per_chain_usd?: 69000 | 250000;
      /**
       * @description Optional custom fee configuration.
       *     Fees are in basis points (100 bps = 1%).
       *     If omitted, defaults are used.
       */
      custom_fees?: {
        bonding_curve_dev_fee_bps?: number;
        amm_dev_fee_bps?: number;
      };
      /**
       * @description Where telecoin fees are directed.
       *     Defaults to "dev" if omitted.
       * @enum {string}
       */
      fee_sink?: "dev" | "stake_pool";
      /**
       * @description Ratio of the telecoin supply sold on the bonding curve, in basis points.
       *     The remainder is deposited into the AMM after graduation.
       *     Can be used to control initial market cap.
       *     See docs for formulas.
       *     Omit or use 0 for a default.
       */
      telecoin_supply_on_curve_ratio_bps?: number;
    };
    /**
     * @description Chain Agnostic Improvement Proposal (CAIP-10) account identifier. Provides a universal format for identifying accounts across different blockchain networks. Format: {namespace}:{reference}:{account_address}
     *
     *     Examples:
     *     - eip155:1:0xc33f294bae8f55554c7b786306eac562d8fe9566 - Ethereum address
     *     - solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp:7S3P4HxJpyyigGzodYwHtCxZyUQe9JiBMHyRWXArAaKv - Solana address
     * @example eip155:1:0xc33f294bae8f55554c7b786306eac562d8fe9566
     */
    CAIP_10_Account: string;
    /** @description A representation of a token or asset associated with a specific chain. */
    Asset: {
      /** @description Reference asset identified as a CAIP-10 Account ID. */
      id: components["schemas"]["CAIP_10_Account"];
      /** @description The name of the asset. */
      name: string;
      /** @description Symbol used to identify the denomination of the asset. */
      symbol: string;
      /** @description The number of decimals used to represent the asset. */
      decimals: number;
      /**
       * Format: double
       * @description The estimated price of the asset in USD.
       */
      price_usd: number;
    };
    Cost: {
      /**
       * @description Reference asset identified as a CAIP-10 Account ID
       * @example eip155:137:0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE
       */
      asset_id: string;
      /**
       * Format: double
       * @example 10.140679211841073
       */
      cost_usd: number;
      /** @description Atomic cost in the reference asset. */
      cost_asset_atomic: components["schemas"]["BigInt"];
      /** @description Descriptor for the cost. */
      description?: string;
      /**
       * Format: int64
       * @description Upper bound spending limit for the cost (if applicable).
       * @example 802300
       */
      limit?: number;
    };
    /** @description Comprehensive cost breakdown for token creation across selected chains. Includes all fees required for deployment, cross-chain messaging, and initial liquidity provision. Use this information to ensure sufficient funds before initiating token creation. */
    Quote: {
      /** @description Unique identifier for the quote. */
      id: string;
      /** @description The routing provider / type simulating the quote. */
      router: string;
      /** @description List of assets involved in the quote. */
      assets: components["schemas"]["Asset"][];
      /** @description The token amount transfered to the creation as part of the initial buy. */
      initial_buy_amount?: components["schemas"]["BigInt"];
      costs: components["schemas"]["Cost"][];
      total: components["schemas"]["Cost"];
    };
    GetPrintQuote_Response: {
      quote: components["schemas"]["Quote"];
    };
    Error: {
      error: {
        /**
         * @description Machine-readable error code
         * @example INVALID_CHAIN
         */
        code: string;
        /**
         * @description Human-readable error message
         * @example The specified chain 'eip155:999' is not supported
         */
        message: string;
        /** @description Additional error context */
        details?: {
          [key: string]: unknown;
        };
        /**
         * Format: uuid
         * @description Unique request identifier for debugging
         * @example 123e4567-e89b-12d3-a456-426614174000
         */
        request_id?: string;
      };
    };
    PrintToken_Request: {
      /**
       * @deprecated
       * @description CAIP-10 account identifier of the token creator.
       */
      creator_account?: components["schemas"]["CAIP_10_Account"];
      /** @description Array of CAIP-10 account identifiers for the token creator. */
      creator_accounts: components["schemas"]["CAIP_10_Account"][];
      name: string;
      symbol: string;
      description: string;
      /** Format: byte */
      image: string;
      /**
       * @description Optional external links related to the telecoin.
       *     Empty strings are ignored.
       */
      external_links?: {
        website?: string;
        x?: string;
        telegram?: string;
        github?: string;
      };
      /** @description Array of chains where the token will be deployed. */
      chains: components["schemas"]["CAIP_2_Chain"][];
      initial_buy: components["schemas"]["VariableInitialBuy"];
      /**
       * @description The graduation threshold (bonding curve size) for each chain deployed to. Accepted values: $69,000 or $250,000 USD. Defaults to $69,000 USD.
       * @enum {integer}
       */
      graduation_threshold_per_chain_usd?: 69000 | 250000;
      /**
       * @description Optional custom fee configuration.
       *     Fees are in basis points (100 bps = 1%).
       *     If omitted, defaults are used.
       */
      custom_fees?: {
        bonding_curve_dev_fee_bps?: number;
        amm_dev_fee_bps?: number;
      };
      /**
       * @description Where telecoin fees are directed.
       *     Defaults to "dev" if omitted.
       * @enum {string}
       */
      fee_sink?: "dev" | "stake_pool";
      /**
       * @description Ratio of the telecoin supply sold on the bonding curve, in basis points.
       *     The remainder is deposited into the AMM after graduation.
       *     Can be used to control initial market cap.
       *     See docs for formulas.
       *     Omit or use 0 for a default.
       */
      telecoin_supply_on_curve_ratio_bps?: number;
    };
    /** Payload (EVM) */
    Payload_Evm: {
      /** @description The CAIP-10 account identifier to send the transaction to. */
      to: components["schemas"]["CAIP_10_Account"];
      /** Format: byte */
      calldata: string;
      value: string;
      /** Format: int64 */
      gas_limit: number;
    };
    Payload_Svm_Ixs_AccountMeta: {
      /** @description Base58-encoded public key. */
      pubkey: string;
      /** @description Whether the account must sign the transaction. */
      is_signer: boolean;
      /** @description Whether the account is writable by the program. */
      is_writable: boolean;
    };
    Payload_Svm_Ixs: {
      /** @description Base58-encoded Solana program id. */
      program_id: string;
      /** @description The accounts to pass to the program in the order they are expected. Can be empty. */
      accounts: components["schemas"]["Payload_Svm_Ixs_AccountMeta"][];
      /** @description Serialized instruction params as a base64 string. */
      data: string;
    };
    /** Payload (SVM) */
    Payload_Svm: {
      /** @description The expected address of the telecoin mint. */
      mint_address: components["schemas"]["CAIP_10_Account"];
      /** @description List of Solana instructions to include in the transaction. */
      ixs: components["schemas"]["Payload_Svm_Ixs"][];
      /** @description Use this lookup table to minimize the tx size. */
      lookup_table?: string;
    };
    Payload: {
      /** Format: byte */
      hash?: string;
    } & (components["schemas"]["Payload_Evm"] | components["schemas"]["Payload_Svm"]);
    PrintToken_Response: {
      /** @description The cross-chain token identifier. */
      token_id: string;
      payload: components["schemas"]["Payload"];
      quote: components["schemas"]["Quote"];
    };
    GetToken_Response: {
      /** @description Cross-chain unique identifier for the token */
      id: string;
      /** @description List of creator addresses for the token */
      creatorAddresses: components["schemas"]["CAIP_10_Account"][];
      /** @description Token name */
      name: string;
      /** @description Token symbol */
      symbol: string;
      /** @description Token description */
      description: string;
      /** @description URL to token image */
      imageUrl: string;
      /** @description External links for the token */
      externalLinks?: {
        website?: string;
        telegram?: string;
        x?: string;
        github?: string;
      };
      /** @description List of chains where token is deployed */
      chains: components["schemas"]["CAIP_2_Chain"][];
      curveProperties: {
        /** @description The origin chain which was used to propagate the other remote creations. */
        homeChain: string;
        /** @description List of base pair addresses for the token */
        basePairAddresses: string[];
        /** @description The reference asset ID for the token */
        referenceAssetId: string;
        /** @description The maximum supply exponent for the token */
        maxSupplyExponent: number;
        /** @description The completion threshold basis points for the token */
        completionThresholdBasisPoints: number;
        /** @description The graduation threshold reference atomic for the token */
        graduationThresholdRefAtomic: string;
        /** @description The initial price reference atomic for the token */
        initialPriceRefAtomic: string;
      };
    };
    XChainDeploymentTransaction: {
      chain_id: components["schemas"]["CAIP_2_Chain"];
      /** @description The message ID to track the x-chain deployment. */
      message_id: string;
      /**
       * @description The provider of the x-chain deployment which the id is relevant to.
       * @enum {string}
       */
      transport?: "AXELAR";
    };
    /** @description Real-time status information for a token's deployment on a specific blockchain. Tracks the complete lifecycle from initial deployment through to trading availability, including cross-chain message propagation for remote chains. */
    TokenDeployment: {
      chain_id: components["schemas"]["CAIP_2_Chain"];
      /** @enum {string} */
      status: "pending" | "deploying" | "live" | "failed";
      x_chain_transaction?: components["schemas"]["XChainDeploymentTransaction"];
      /** Format: double */
      graduation_completion_percent?: number;
      contract_address?: string;
      transaction_id?: string;
      /** Format: int64 */
      block_ts_secs?: number;
    };
    GetTokenStatus_Response: {
      deployments: components["schemas"]["TokenDeployment"][];
    };
  };
  responses: {
    /**
     * @description The request contains invalid parameters or violates API constraints. Common causes:
     *     - Invalid CAIP-2 chain identifier format
     *     - Unsupported blockchain network specified
     *     - Missing required fields in request body
     *     - Invalid initial buy configuration (e.g., percentage > 100%)
     *     - Token metadata exceeds size limits
     */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /**
     * @description Authentication failed or required credentials are missing. Ensure:
     *     - Valid OAuth2 token is included in the Authorization header
     *     - Token has required scopes for the requested operation
     *     - Token has not expired
     */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "UNAUTHORIZED",
         *         "message": "Invalid or expired access token"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /**
     * @description Request rate limit exceeded. The API implements rate limiting to ensure fair usage:
     *     - Check X-RateLimit headers for limit details
     *     - Implement exponential backoff for retries
     *     - Consider caching responses where appropriate
     */
    RateLimited: {
      headers: {
        /**
         * @description Request limit per hour
         * @example 100
         */
        "X-RateLimit-Limit"?: number;
        /**
         * @description Remaining requests in current window
         * @example 0
         */
        "X-RateLimit-Remaining"?: number;
        /**
         * @description Unix timestamp when rate limit resets
         * @example 1642338000
         */
        "X-RateLimit-Reset"?: number;
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "RATE_LIMITED",
         *         "message": "Rate limit exceeded. Please retry after 1642338000"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /**
     * @description An unexpected error occurred processing the request. These are typically transient issues:
     *     - Retry with exponential backoff
     *     - Check Printr status page for system-wide issues
     *     - Contact support if errors persist with request_id for debugging
     */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
        example: unknown;
      };
    };
    /**
     * @description The requested resource does not exist. This can occur when:
     *     - Token ID does not match any created tokens
     *     - Token exists but has no deployments yet
     *     - Attempting to access tokens from other platforms not yet indexed
     */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "NOT_FOUND",
         *         "message": "Token not found"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getPrintQuote: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GetPrintQuote_Request"];
      };
    };
    responses: {
      /** @description Quote calculated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetPrintQuote_Response"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  printToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PrintToken_Request"];
      };
    };
    responses: {
      /** @description Token registered in Printr's catalog. Waiting for on-chain events to complete. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrintToken_Response"];
        };
      };
    };
  };
  getToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Telecoin ID or CAIP-10 CA */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token information retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetToken_Response"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  getTokenStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Telecoin ID or CAIP-10 CA */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token deployment status retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetTokenStatus_Response"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
}
