use anyhow::Result;
use dashmap::DashMap;
use log::{debug, info, warn};
use tokio::sync::{broadcast, mpsc};

use crate::commands::command::Command;
use crate::engine::event_bus::EventBus;
use crate::engine::executor::Executor;
use crate::engine::state::{apply_new_token, apply_trade, TokenStore};
use crate::models::events::EngineEvent;
use crate::settings::settings::SniperSettings;
use crate::strategies::strategy::Strategy;

pub struct Engine {
    strategies: Vec<Box<dyn Strategy + Send>>,
    token_state: TokenStore,
    command_rx: mpsc::Receiver<Command>,
    event_rx: broadcast::Receiver<EngineEvent>,
    executor: Executor,
    running: bool,
}

impl Engine {
    pub fn new() -> (Self, EventBus) {
        let (event_tx, event_rx) = broadcast::channel(1024);
        let (command_tx, command_rx) = mpsc::channel(128);

        let engine = Self {
            strategies: Vec::new(),
            token_state: DashMap::new(),
            command_rx,
            event_rx,
            executor: Executor::new(),
            running: false,
        };

        (engine, EventBus::new(event_tx, command_tx))
    }

    pub fn register_strategy(&mut self, strategy: Box<dyn Strategy + Send>) {
        info!("[ENGINE] Registered strategy {}", strategy.name());
        self.strategies.push(strategy);
    }

    pub async fn run(&mut self) -> Result<()> {
        info!("[ENGINE] event loop started");

        loop {
            tokio::select! {
                maybe_command = self.command_rx.recv() => {
                    match maybe_command {
                        Some(command) => self.handle_command(command),
                        None => {
                            warn!("[ENGINE] command channel closed");
                            break;
                        }
                    }
                }
                event_result = self.event_rx.recv() => {
                    match event_result {
                        Ok(event) => {
                            if !self.running {
                                debug!("[ENGINE] event dropped (engine stopped)");
                                continue;
                            }
                            self.handle_event(event).await;
                        }
                        Err(broadcast::error::RecvError::Lagged(skipped)) => {
                            warn!("[ENGINE] lagged on event stream, skipped {skipped} events");
                        }
                        Err(broadcast::error::RecvError::Closed) => {
                            warn!("[ENGINE] event channel closed");
                            break;
                        }
                    }
                }
            }
        }

        info!("[ENGINE] event loop stopped");
        Ok(())
    }

    fn handle_command(&mut self, command: Command) {
        match command {
            Command::StartBot => {
                self.running = true;
                info!("[ENGINE] StartBot received");
            }
            Command::StopBot => {
                self.running = false;
                info!("[ENGINE] StopBot received");
            }
            Command::UpdateSettings(settings) => {
                info!("[ENGINE] UpdateSettings received: {:?}", settings);
                for strategy in &mut self.strategies {
                    strategy.update_settings(&settings);
                }
            }
        }
    }

    async fn handle_event(&mut self, event: EngineEvent) {
        info!("[ENGINE] event received: {event:?}");

        match event {
            EngineEvent::Trade(trade) => {
                apply_trade(&self.token_state, &trade);

                for strategy in &mut self.strategies {
                    if let Some(order) = strategy.on_trade(&trade) {
                        info!(
                            "[STRATEGY] order generated by {} for {}",
                            strategy.name(),
                            trade.token_mint
                        );
                        if let Err(err) = self.executor.execute(order).await {
                            log::error!("[EXECUTOR] execution error: {err}");
                        }
                    }
                }
            }
            EngineEvent::NewToken(token) => {
                apply_new_token(&self.token_state, &token);

                for strategy in &mut self.strategies {
                    if let Some(order) = strategy.on_new_token(&token) {
                        info!(
                            "[STRATEGY] order generated by {} for {}",
                            strategy.name(),
                            token.mint
                        );
                        if let Err(err) = self.executor.execute(order).await {
                            log::error!("[EXECUTOR] execution error: {err}");
                        }
                    }
                }
            }
        }
    }
}
