// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chains/chains.proto (package printrfi.chains, syntax proto3)
/* eslint-disable */
// @ts-nocheck
import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum printrfi.chains.Status
 */
export enum Status {
  /**
   * @generated from enum value: ACTIVE = 0;
   */
  ACTIVE = 0,

  /**
   * @generated from enum value: DISABLED = 1;
   */
  DISABLED = 1,

  /**
   * @generated from enum value: COMING_SOON = 2;
   */
  COMING_SOON = 2,

  /**
   * @generated from enum value: DEPRECATED = 3;
   */
  DEPRECATED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(Status)
proto3.util.setEnumType(Status, "printrfi.chains.Status", [
  { no: 0, name: "ACTIVE" },
  { no: 1, name: "DISABLED" },
  { no: 2, name: "COMING_SOON" },
  { no: 3, name: "DEPRECATED" },
]);

/**
 * @generated from enum printrfi.chains.NetworkEnvironment
 */
export enum NetworkEnvironment {
  /**
   * @generated from enum value: MAINNET = 0;
   */
  MAINNET = 0,

  /**
   * @generated from enum value: TESTNET = 1;
   */
  TESTNET = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(NetworkEnvironment)
proto3.util.setEnumType(NetworkEnvironment, "printrfi.chains.NetworkEnvironment", [
  { no: 0, name: "MAINNET" },
  { no: 1, name: "TESTNET" },
]);

/**
 * @generated from enum printrfi.chains.Platform
 */
export enum Platform {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: EVM = 1;
   */
  EVM = 1,

  /**
   * @generated from enum value: SOLANA = 2;
   */
  SOLANA = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(Platform)
proto3.util.setEnumType(Platform, "printrfi.chains.Platform", [
  { no: 0, name: "UNKNOWN" },
  { no: 1, name: "EVM" },
  { no: 2, name: "SOLANA" },
]);

/**
 * @generated from message printrfi.chains.NativeCurrency
 */
export class NativeCurrency extends Message<NativeCurrency> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string symbol = 2;
   */
  symbol = "";

  /**
   * @generated from field: int32 decimals = 3;
   */
  decimals = 0;

  constructor(data?: PartialMessage<NativeCurrency>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.chains.NativeCurrency";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "symbol", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "decimals", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NativeCurrency {
    return new NativeCurrency().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NativeCurrency {
    return new NativeCurrency().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NativeCurrency {
    return new NativeCurrency().fromJsonString(jsonString, options);
  }

  static equals(
    a: NativeCurrency | PlainMessage<NativeCurrency> | undefined,
    b: NativeCurrency | PlainMessage<NativeCurrency> | undefined,
  ): boolean {
    return proto3.util.equals(NativeCurrency, a, b);
  }
}

/**
 * @generated from message printrfi.chains.Chain
 */
export class Chain extends Message<Chain> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: printrfi.chains.Platform platform = 2;
   */
  platform = Platform.UNKNOWN;

  /**
   * @generated from field: printrfi.chains.Status status = 3;
   */
  status = Status.ACTIVE;

  /**
   * @generated from field: string name = 4;
   */
  name = "";

  /**
   * @generated from field: printrfi.chains.NativeCurrency native_currency = 5;
   */
  nativeCurrency?: NativeCurrency;

  /**
   * @generated from field: string info_url = 6;
   */
  infoUrl = "";

  constructor(data?: PartialMessage<Chain>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.chains.Chain";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "platform", kind: "enum", T: proto3.getEnumType(Platform) },
    { no: 3, name: "status", kind: "enum", T: proto3.getEnumType(Status) },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "native_currency", kind: "message", T: NativeCurrency },
    { no: 6, name: "info_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Chain {
    return new Chain().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Chain {
    return new Chain().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Chain {
    return new Chain().fromJsonString(jsonString, options);
  }

  static equals(
    a: Chain | PlainMessage<Chain> | undefined,
    b: Chain | PlainMessage<Chain> | undefined,
  ): boolean {
    return proto3.util.equals(Chain, a, b);
  }
}
