// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/misc.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Account } from "../caip/account_pb.js";

/**
 * @generated from enum printrfi.wingman.PartnerKind
 */
export enum PartnerKind {
  /**
   * @generated from enum value: UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LZ = 1;
   */
  LZ = 1,

  /**
   * @generated from enum value: DEBRIDGE = 2;
   */
  DEBRIDGE = 2,

  /**
   * @generated from enum value: RELAY_LINK = 3;
   */
  RELAY_LINK = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(PartnerKind)
proto3.util.setEnumType(PartnerKind, "printrfi.wingman.PartnerKind", [
  { no: 0, name: "UNSPECIFIED" },
  { no: 1, name: "LZ" },
  { no: 2, name: "DEBRIDGE" },
  { no: 3, name: "RELAY_LINK" },
]);

/**
 * Basic building primitive in Solana
 *
 * @generated from message printrfi.wingman.Base58Pubkey
 */
export class Base58Pubkey extends Message<Base58Pubkey> {
  /**
   * Required.
   *
   * TODO: rename to "address"?
   *
   * @generated from field: string value = 1;
   */
  value = "";

  constructor(data?: PartialMessage<Base58Pubkey>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.Base58Pubkey";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Base58Pubkey {
    return new Base58Pubkey().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Base58Pubkey {
    return new Base58Pubkey().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Base58Pubkey {
    return new Base58Pubkey().fromJsonString(jsonString, options);
  }

  static equals(
    a: Base58Pubkey | PlainMessage<Base58Pubkey> | undefined,
    b: Base58Pubkey | PlainMessage<Base58Pubkey> | undefined,
  ): boolean {
    return proto3.util.equals(Base58Pubkey, a, b);
  }
}

/**
 * Used to create a Solana ix
 *
 * @generated from message printrfi.wingman.AccountMeta
 */
export class AccountMeta extends Message<AccountMeta> {
  /**
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey pubkey = 1;
   */
  pubkey?: Base58Pubkey;

  /**
   * Required.
   *
   * @generated from field: bool is_signer = 2;
   */
  isSigner = false;

  /**
   * Required.
   *
   * @generated from field: bool is_writable = 3;
   */
  isWritable = false;

  constructor(data?: PartialMessage<AccountMeta>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.AccountMeta";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pubkey", kind: "message", T: Base58Pubkey },
    { no: 2, name: "is_signer", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "is_writable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AccountMeta {
    return new AccountMeta().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AccountMeta {
    return new AccountMeta().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AccountMeta {
    return new AccountMeta().fromJsonString(jsonString, options);
  }

  static equals(
    a: AccountMeta | PlainMessage<AccountMeta> | undefined,
    b: AccountMeta | PlainMessage<AccountMeta> | undefined,
  ): boolean {
    return proto3.util.equals(AccountMeta, a, b);
  }
}

/**
 * Solana ixs can be used to build a tx
 *
 * @generated from message printrfi.wingman.SolanaIx
 */
export class SolanaIx extends Message<SolanaIx> {
  /**
   * Which program to call.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey program_id = 1;
   */
  programId?: Base58Pubkey;

  /**
   * The accounts to pass to the program in the order they are expected.
   *
   * Required.
   * Can be empty.
   *
   * @generated from field: repeated printrfi.wingman.AccountMeta accounts = 2;
   */
  accounts: AccountMeta[] = [];

  /**
   * Serialized ix params into base64 string.
   *
   * Required.
   *
   * @generated from field: string data = 3;
   */
  data = "";

  constructor(data?: PartialMessage<SolanaIx>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaIx";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "program_id", kind: "message", T: Base58Pubkey },
    { no: 2, name: "accounts", kind: "message", T: AccountMeta, repeated: true },
    { no: 3, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaIx {
    return new SolanaIx().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaIx {
    return new SolanaIx().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaIx {
    return new SolanaIx().fromJsonString(jsonString, options);
  }

  static equals(
    a: SolanaIx | PlainMessage<SolanaIx> | undefined,
    b: SolanaIx | PlainMessage<SolanaIx> | undefined,
  ): boolean {
    return proto3.util.equals(SolanaIx, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.EvmTx
 */
export class EvmTx extends Message<EvmTx> {
  /**
   * Where to send the tx to.
   *
   * @generated from field: printrfi.caip.Account target_contract = 1;
   */
  targetContract?: Account;

  /**
   * Gas limit to use for the transaction.
   *
   * Optional, is zero if not set in which case a simulation or a constant gas limit should be used.
   *
   * @generated from field: uint64 gas_limit = 2;
   */
  gasLimit = protoInt64.zero;

  /**
   * Native value to send with the transaction in the respective chain's smallest denomination.
   *
   * @generated from field: string msg_value = 3;
   */
  msgValue = "";

  /**
   * Expecting EVM calldata starting with "0x" prefix.
   *
   * @generated from field: string hex_encoded_prefixed_calldata = 4;
   */
  hexEncodedPrefixedCalldata = "";

  constructor(data?: PartialMessage<EvmTx>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EvmTx";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_contract", kind: "message", T: Account },
    { no: 2, name: "gas_limit", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "msg_value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "hex_encoded_prefixed_calldata", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EvmTx {
    return new EvmTx().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EvmTx {
    return new EvmTx().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EvmTx {
    return new EvmTx().fromJsonString(jsonString, options);
  }

  static equals(
    a: EvmTx | PlainMessage<EvmTx> | undefined,
    b: EvmTx | PlainMessage<EvmTx> | undefined,
  ): boolean {
    return proto3.util.equals(EvmTx, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.QuotedEvmTx
 */
export class QuotedEvmTx extends Message<QuotedEvmTx> {
  /**
   * Where to send the tx to.
   *
   * @generated from field: printrfi.caip.Account target_contract = 1;
   */
  targetContract?: Account;

  /**
   * Gas limit to use for the transaction.
   *
   * @generated from field: uint64 gas_limit = 2;
   */
  gasLimit = protoInt64.zero;

  /**
   * Native value to send with the transaction in the respective chain's smallest denomination.
   *
   * @generated from field: string msg_value = 3;
   */
  msgValue = "";

  constructor(data?: PartialMessage<QuotedEvmTx>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.QuotedEvmTx";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_contract", kind: "message", T: Account },
    { no: 2, name: "gas_limit", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "msg_value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QuotedEvmTx {
    return new QuotedEvmTx().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QuotedEvmTx {
    return new QuotedEvmTx().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QuotedEvmTx {
    return new QuotedEvmTx().fromJsonString(jsonString, options);
  }

  static equals(
    a: QuotedEvmTx | PlainMessage<QuotedEvmTx> | undefined,
    b: QuotedEvmTx | PlainMessage<QuotedEvmTx> | undefined,
  ): boolean {
    return proto3.util.equals(QuotedEvmTx, a, b);
  }
}

/**
 * The ubiquitous on-chain token params structure.
 *
 * @generated from message printrfi.wingman.TelecoinParams
 */
export class TelecoinParams extends Message<TelecoinParams> {
  /**
   * Required.
   *
   * @generated from field: bytes salt = 1;
   */
  salt = new Uint8Array(0);

  /**
   * Required.
   *
   * @generated from field: bytes creator_addresses = 2;
   */
  creatorAddresses = new Uint8Array(0);

  /**
   * Required.
   *
   * @generated from field: bytes name = 3;
   */
  name = new Uint8Array(0);

  /**
   * Required.
   *
   * @generated from field: bytes symbol = 4;
   */
  symbol = new Uint8Array(0);

  /**
   * Required.
   *
   * @generated from field: bytes packed_params = 5;
   */
  packedParams = new Uint8Array(0);

  /**
   * Required.
   *
   * @generated from field: bytes chains = 6;
   */
  chains = new Uint8Array(0);

  /**
   * Required.
   *
   * @generated from field: bytes quote_pairs = 7;
   */
  quotePairs = new Uint8Array(0);

  /**
   * Required.
   *
   * @generated from field: bytes quote_prices = 8;
   */
  quotePrices = new Uint8Array(0);

  constructor(data?: PartialMessage<TelecoinParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.TelecoinParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "salt", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "creator_addresses", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "name", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "symbol", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "packed_params", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 6, name: "chains", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 7, name: "quote_pairs", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 8, name: "quote_prices", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TelecoinParams {
    return new TelecoinParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TelecoinParams {
    return new TelecoinParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TelecoinParams {
    return new TelecoinParams().fromJsonString(jsonString, options);
  }

  static equals(
    a: TelecoinParams | PlainMessage<TelecoinParams> | undefined,
    b: TelecoinParams | PlainMessage<TelecoinParams> | undefined,
  ): boolean {
    return proto3.util.equals(TelecoinParams, a, b);
  }
}

/**
 * Identifies some amount of a specific asset.
 *
 * @generated from message printrfi.wingman.AssetAmount
 */
export class AssetAmount extends Message<AssetAmount> {
  /**
   * Required.
   *
   * @generated from field: printrfi.caip.Account asset = 1;
   */
  asset?: Account;

  /**
   * Required.
   *
   * @generated from field: printrfi.wingman.TokenAmount amount = 2;
   */
  amount?: TokenAmount;

  constructor(data?: PartialMessage<AssetAmount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.AssetAmount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset", kind: "message", T: Account },
    { no: 2, name: "amount", kind: "message", T: TokenAmount },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AssetAmount {
    return new AssetAmount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AssetAmount {
    return new AssetAmount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AssetAmount {
    return new AssetAmount().fromJsonString(jsonString, options);
  }

  static equals(
    a: AssetAmount | PlainMessage<AssetAmount> | undefined,
    b: AssetAmount | PlainMessage<AssetAmount> | undefined,
  ): boolean {
    return proto3.util.equals(AssetAmount, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.TokenAmount
 */
export class TokenAmount extends Message<TokenAmount> {
  /**
   * In the respective token's smallest denomination.
   *
   * Required.
   *
   * @generated from field: string atomic = 1;
   */
  atomic = "";

  /**
   * Formatted with appropriate decimal places.
   *
   * Required.
   *
   * @generated from field: string display = 2;
   */
  display = "";

  /**
   * Number of decimals the token uses.
   *
   * @generated from field: uint32 decimals = 3;
   */
  decimals = 0;

  constructor(data?: PartialMessage<TokenAmount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.TokenAmount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "atomic", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "decimals", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TokenAmount {
    return new TokenAmount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TokenAmount {
    return new TokenAmount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TokenAmount {
    return new TokenAmount().fromJsonString(jsonString, options);
  }

  static equals(
    a: TokenAmount | PlainMessage<TokenAmount> | undefined,
    b: TokenAmount | PlainMessage<TokenAmount> | undefined,
  ): boolean {
    return proto3.util.equals(TokenAmount, a, b);
  }
}

/**
 * / A version of the Printr protocol is always related to a specific chain.
 *
 * @generated from message printrfi.wingman.PrintrProtocolVersion
 */
export class PrintrProtocolVersion extends Message<PrintrProtocolVersion> {
  /**
   * @generated from field: uint32 version = 1;
   */
  version = 0;

  constructor(data?: PartialMessage<PrintrProtocolVersion>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.PrintrProtocolVersion";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PrintrProtocolVersion {
    return new PrintrProtocolVersion().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PrintrProtocolVersion {
    return new PrintrProtocolVersion().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PrintrProtocolVersion {
    return new PrintrProtocolVersion().fromJsonString(jsonString, options);
  }

  static equals(
    a: PrintrProtocolVersion | PlainMessage<PrintrProtocolVersion> | undefined,
    b: PrintrProtocolVersion | PlainMessage<PrintrProtocolVersion> | undefined,
  ): boolean {
    return proto3.util.equals(PrintrProtocolVersion, a, b);
  }
}

/**
 * / Conveys an asset price in USD.
 *
 * @generated from message printrfi.wingman.UsdPricedAsset
 */
export class UsdPricedAsset extends Message<UsdPricedAsset> {
  /**
   * / Required.
   *
   * @generated from field: printrfi.caip.Account asset = 1;
   */
  asset?: Account;

  /**
   * / Required.
   *
   * @generated from field: printrfi.wingman.Price price = 3;
   */
  price?: Price;

  constructor(data?: PartialMessage<UsdPricedAsset>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.UsdPricedAsset";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset", kind: "message", T: Account },
    { no: 3, name: "price", kind: "message", T: Price },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsdPricedAsset {
    return new UsdPricedAsset().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsdPricedAsset {
    return new UsdPricedAsset().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsdPricedAsset {
    return new UsdPricedAsset().fromJsonString(jsonString, options);
  }

  static equals(
    a: UsdPricedAsset | PlainMessage<UsdPricedAsset> | undefined,
    b: UsdPricedAsset | PlainMessage<UsdPricedAsset> | undefined,
  ): boolean {
    return proto3.util.equals(UsdPricedAsset, a, b);
  }
}

/**
 * / Conveys an asset price in some reference currency to the caller.
 *
 * @generated from message printrfi.wingman.PricedAsset
 */
export class PricedAsset extends Message<PricedAsset> {
  /**
   * / The asset being priced.
   * /
   * / Required.
   *
   * @generated from field: printrfi.caip.Account asset = 1;
   */
  asset?: Account;

  /**
   * / The reference currency in which the price is expressed.
   * /
   * / Required.
   *
   * @generated from field: printrfi.caip.Account reference = 2;
   */
  reference?: Account;

  /**
   * / Required.
   *
   * @generated from field: printrfi.wingman.Price price = 3;
   */
  price?: Price;

  constructor(data?: PartialMessage<PricedAsset>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.PricedAsset";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset", kind: "message", T: Account },
    { no: 2, name: "reference", kind: "message", T: Account },
    { no: 3, name: "price", kind: "message", T: Price },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PricedAsset {
    return new PricedAsset().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PricedAsset {
    return new PricedAsset().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PricedAsset {
    return new PricedAsset().fromJsonString(jsonString, options);
  }

  static equals(
    a: PricedAsset | PlainMessage<PricedAsset> | undefined,
    b: PricedAsset | PlainMessage<PricedAsset> | undefined,
  ): boolean {
    return proto3.util.equals(PricedAsset, a, b);
  }
}

/**
 * / Price of an asset in some reference currency.
 *
 * @generated from message printrfi.wingman.Price
 */
export class Price extends Message<Price> {
  /**
   * / One of asset in worth this much reference.
   * /
   * / E.g. 1 $SOL = 213 $USDC would be "213.0".
   * /
   * / Required.
   *
   * @generated from field: string display = 1;
   */
  display = "";

  /**
   * / Price scaled by 10^18 for precision.
   * /
   * / E.g. 1 $SOL = 213 $USDC would be "213000000000000000000".
   * /
   * / Required.
   *
   * @generated from field: string x18 = 2;
   */
  x18 = "";

  constructor(data?: PartialMessage<Price>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.Price";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "display", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "x18", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Price {
    return new Price().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Price {
    return new Price().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Price {
    return new Price().fromJsonString(jsonString, options);
  }

  static equals(
    a: Price | PlainMessage<Price> | undefined,
    b: Price | PlainMessage<Price> | undefined,
  ): boolean {
    return proto3.util.equals(Price, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaTx
 */
export class SolanaTx extends Message<SolanaTx> {
  /**
   * The ixs with which to build a tx.
   *
   * Required.
   *
   * @generated from field: repeated printrfi.wingman.SolanaIx ixs = 1;
   */
  ixs: SolanaIx[] = [];

  /**
   * Use this lookup table to minimize the tx size.
   *
   * Optional.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey lookup_table = 2;
   */
  lookupTable?: Base58Pubkey;

  constructor(data?: PartialMessage<SolanaTx>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaTx";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ixs", kind: "message", T: SolanaIx, repeated: true },
    { no: 2, name: "lookup_table", kind: "message", T: Base58Pubkey },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaTx {
    return new SolanaTx().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaTx {
    return new SolanaTx().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaTx {
    return new SolanaTx().fromJsonString(jsonString, options);
  }

  static equals(
    a: SolanaTx | PlainMessage<SolanaTx> | undefined,
    b: SolanaTx | PlainMessage<SolanaTx> | undefined,
  ): boolean {
    return proto3.util.equals(SolanaTx, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.PlatformPayload
 */
export class PlatformPayload extends Message<PlatformPayload> {
  /**
   * @generated from oneof printrfi.wingman.PlatformPayload.payload
   */
  payload:
    | {
        /**
         * @generated from field: printrfi.wingman.EvmTx evm = 1;
         */
        value: EvmTx;
        case: "evm";
      }
    | {
        /**
         * @generated from field: printrfi.wingman.SolanaTx solana = 2;
         */
        value: SolanaTx;
        case: "solana";
      }
    | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<PlatformPayload>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.PlatformPayload";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "evm", kind: "message", T: EvmTx, oneof: "payload" },
    { no: 2, name: "solana", kind: "message", T: SolanaTx, oneof: "payload" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlatformPayload {
    return new PlatformPayload().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlatformPayload {
    return new PlatformPayload().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlatformPayload {
    return new PlatformPayload().fromJsonString(jsonString, options);
  }

  static equals(
    a: PlatformPayload | PlainMessage<PlatformPayload> | undefined,
    b: PlatformPayload | PlainMessage<PlatformPayload> | undefined,
  ): boolean {
    return proto3.util.equals(PlatformPayload, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.XchainIntent
 */
export class XchainIntent extends Message<XchainIntent> {
  /**
   * @generated from field: printrfi.wingman.XchainRoute route = 1;
   */
  route?: XchainRoute;

  /**
   * The `route` gives this its meaning.
   *
   * @generated from field: string request_id = 2;
   */
  requestId = "";

  constructor(data?: PartialMessage<XchainIntent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.XchainIntent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "route", kind: "message", T: XchainRoute },
    { no: 2, name: "request_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): XchainIntent {
    return new XchainIntent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): XchainIntent {
    return new XchainIntent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): XchainIntent {
    return new XchainIntent().fromJsonString(jsonString, options);
  }

  static equals(
    a: XchainIntent | PlainMessage<XchainIntent> | undefined,
    b: XchainIntent | PlainMessage<XchainIntent> | undefined,
  ): boolean {
    return proto3.util.equals(XchainIntent, a, b);
  }
}

/**
 * {\.${protocol}}{*}{\.${partner}}{1}
 *
 * @generated from message printrfi.wingman.XchainRoute
 */
export class XchainRoute extends Message<XchainRoute> {
  /**
   * E.g. "intent-address", "gmp", "oapp", "posthook" etc.
   * Can be empty if not applicable.
   *
   * @generated from field: repeated string protocol = 1;
   */
  protocol: string[] = [];

  /**
   * @generated from field: printrfi.wingman.PartnerKind partner = 2;
   */
  partner = PartnerKind.UNSPECIFIED;

  constructor(data?: PartialMessage<XchainRoute>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.XchainRoute";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "protocol", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "partner", kind: "enum", T: proto3.getEnumType(PartnerKind) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): XchainRoute {
    return new XchainRoute().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): XchainRoute {
    return new XchainRoute().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): XchainRoute {
    return new XchainRoute().fromJsonString(jsonString, options);
  }

  static equals(
    a: XchainRoute | PlainMessage<XchainRoute> | undefined,
    b: XchainRoute | PlainMessage<XchainRoute> | undefined,
  ): boolean {
    return proto3.util.equals(XchainRoute, a, b);
  }
}

/**
 * Contains information about telecoin state when printing it.
 * This is a time-less information derived purely from the telecoin params w/ respect to a chain.
 *
 * @generated from message printrfi.wingman.TelecoinInstance
 */
export class TelecoinInstance extends Message<TelecoinInstance> {
  /**
   * The telecoin id that these token params correspond to.
   *
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * The address of the bonding curve pool.
   *
   * @generated from field: printrfi.caip.Account bonding_curve = 2;
   */
  bondingCurve?: Account;

  /**
   * Initial spend in quote token.
   *
   * @generated from field: printrfi.wingman.AssetAmount initial_spend = 3;
   */
  initialSpend?: AssetAmount;

  /**
   * The amount of quote token that must be collected on the bonding curve before graduation.
   *
   * @generated from field: printrfi.wingman.AssetAmount graduation_quote_reserve = 4;
   */
  graduationQuoteReserve?: AssetAmount;

  /**
   * The price of the telecoin asset in quote token when the curve was created
   * (before initial spend).
   *
   * @generated from field: printrfi.wingman.PricedAsset initial_telecoin_price = 5;
   */
  initialTelecoinPrice?: PricedAsset;

  constructor(data?: PartialMessage<TelecoinInstance>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.TelecoinInstance";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "bonding_curve", kind: "message", T: Account },
    { no: 3, name: "initial_spend", kind: "message", T: AssetAmount },
    { no: 4, name: "graduation_quote_reserve", kind: "message", T: AssetAmount },
    { no: 5, name: "initial_telecoin_price", kind: "message", T: PricedAsset },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TelecoinInstance {
    return new TelecoinInstance().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TelecoinInstance {
    return new TelecoinInstance().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TelecoinInstance {
    return new TelecoinInstance().fromJsonString(jsonString, options);
  }

  static equals(
    a: TelecoinInstance | PlainMessage<TelecoinInstance> | undefined,
    b: TelecoinInstance | PlainMessage<TelecoinInstance> | undefined,
  ): boolean {
    return proto3.util.equals(TelecoinInstance, a, b);
  }
}

/**
 * Contains information about some xchain intent that can be used to perform some action either
 * single or multi chain.
 *
 * @generated from message printrfi.wingman.TxInfo
 */
export class TxInfo extends Message<TxInfo> {
  /**
   * Info about the route.
   *
   * Empty if single chain.
   *
   * @generated from field: optional printrfi.wingman.XchainIntent intent = 1;
   */
  intent?: XchainIntent;

  /**
   * How much will the user spend on xchain fee.
   *
   * Zero if single chain.
   *
   * @generated from field: printrfi.wingman.AssetAmount xchain_fee_cost = 2;
   */
  xchainFeeCost?: AssetAmount;

  /**
   * How much will the user spend on the tx.
   *
   * @generated from field: printrfi.wingman.AssetAmount source_gas_cost = 3;
   */
  sourceGasCost?: AssetAmount;

  /**
   * How much in total will the user spend on source.
   *
   * @generated from field: printrfi.wingman.AssetAmount spend_on_source = 4;
   */
  spendOnSource?: AssetAmount;

  constructor(data?: PartialMessage<TxInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.TxInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "intent", kind: "message", T: XchainIntent, opt: true },
    { no: 2, name: "xchain_fee_cost", kind: "message", T: AssetAmount },
    { no: 3, name: "source_gas_cost", kind: "message", T: AssetAmount },
    { no: 4, name: "spend_on_source", kind: "message", T: AssetAmount },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TxInfo {
    return new TxInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TxInfo {
    return new TxInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TxInfo {
    return new TxInfo().fromJsonString(jsonString, options);
  }

  static equals(
    a: TxInfo | PlainMessage<TxInfo> | undefined,
    b: TxInfo | PlainMessage<TxInfo> | undefined,
  ): boolean {
    return proto3.util.equals(TxInfo, a, b);
  }
}
