// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file pig/pig.proto (package printrfi.pig, syntax proto3)
/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint/suspicious/noShadowRestrictedNames: Generated proto code
import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message printrfi.pig.BigInt
 */
export class BigInt extends Message<BigInt> {
  /**
   * @generated from field: string base_10 = 1;
   */
  base10 = "";

  constructor(data?: PartialMessage<BigInt>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.pig.BigInt";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "base_10", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BigInt {
    return new BigInt().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BigInt {
    return new BigInt().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BigInt {
    return new BigInt().fromJsonString(jsonString, options);
  }

  static equals(
    a: BigInt | PlainMessage<BigInt> | undefined,
    b: BigInt | PlainMessage<BigInt> | undefined,
  ): boolean {
    return proto3.util.equals(BigInt, a, b);
  }
}
